title: "3l1070r"
description: "Staff Engineer | Software Architecture | Security"
baseurl: ""
url: "https://3l1070r.dev"

remote_theme: pages-themes/cayman@v0.2.0

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Author
author:
  name: "Elio Rincón"
  github: "3l1070r"
  linkedin: "3l1070r"