title: "3l1070r"
description: "Staff Engineer | Software Architecture | CyberSecurity"
baseurl: ""
url: "https://3l1070r.dev"

# Minimal Mistakes theme
remote_theme: mmistakes/minimal-mistakes@4.24.0

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-gist

# Site settings
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true
search_full_content: true

# Pagination
paginate: 5
paginate_path: /page:num/

# Comments (Utterances - GitHub based)
comments:
  provider: "utterances"
  utterances:
    theme: "github-dark"
    issue_term: "pathname"
    label: "comment"

# Analytics (opcional)
analytics:
  provider: "google-gtag"
  google:
    tracking_id: # Tu Google Analytics ID aquí

# Author
author:
  name: "Elio Rincón"
  avatar: # URL de tu foto (opcional)
  bio: "Staff Engineer passionate about building scalable systems and exploring security technologies."
  location: "Bogotá, Colombia"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/3l1070r"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/3l1070r/"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/3l1070r"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/3l1070r/"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      classes: wide

# Categories and tags
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/