title: "3l1070r"
description: "Staff Engineer | Software Architecture | CyberSecurity"
baseurl: ""
url: "https://3l1070r.dev"

remote_theme: mmistakes/minimal-mistakes@4.24.0

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-gist

minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true
search_full_content: true

paginate: 5
paginate_path: /page:num/

languages: ["en", "es"]
default_locale: "en"
locale: "en_US"

comments:
  provider: "utterances"
  utterances:
    theme: "github-dark"
    issue_term: "pathname"
    label: "comment"
    repo: "3l1070r/3l1070r.github.io"

repository: "3l1070r/3l1070r.github.io"

gtm_id: "GTM-WQ3GXLFP"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-T0GCL4VHMY"
    anonymize_ip: false

author:
  name: "Elio Rincón"
  avatar: "https://gravatar.com/avatar/7407976f3a4cab233e085bf055d4d96f?s=400&d=robohash&r=x"
  bio: "Lead Engineer passionate about building and architecting scalable software solutions. Deeply interested in cybersecurity, robust Linux/FreeBSD infrastructure, and Bitcoin technology."
  location: "Bogotá, Colombia"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/3l1070r"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/3l1070r/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/3l1070r"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/3l1070r/"

defaults:
  - scope:
      path: "_posts/en"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      classes: wide
      lang: en
  - scope:
      path: "_posts/es"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      classes: wide
      lang: es
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      classes: wide
  - scope:
      path: "en/"
      type: pages
    values:
      layout: single
      author_profile: true
      lang: en
  - scope:
      path: "es/"
      type: pages
    values:
      layout: single
      author_profile: true
      lang: es

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/